// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CustomFieldModalController from "./custom_field_modal_controller"
application.register("custom-field-modal", CustomFieldModalController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfilesController from "./profiles_controller"
application.register("profiles", ProfilesController)
